### PR TITLE
Changed some colors and added option to customize background color, font color and font size.

### PR DESCRIPTION
**Pull request by ingridt123**
screen shot 2016-10-23 at 9 22 51 pm

### CODE REVIEW

**Comment by Arthelon** [comment]
@ingridt123 there are unresolved conflict markers at lines 190-194 in background.js, in styles.css and perhaps many other files.

**Comment by ingridt123** [comment]
Should work now

**Comment by Arthelon** [comment]
@ingridt123 What exactly does that "Customize" text field do? As far as I can tell it is just saved into local storage and redisplayed

**Comment by ingridt123** [comment]
@Arthelon With the "Customize" text field you can customize the background color / font size / font color (depending on which menu is chosen). Just made small changes to placeholder and hover text to make them easier to understand.
Example below changes background color from white to black by entering the hex value into the text field and pressing enter:
screen shot 2016-10-24 at 4 52 47 pmscreen shot 2016-10-24 at 4 53 22 pm

**Comment by Arthelon** [comment]
@ingridt123 nothing (user-facing) happens when an invalid value is entered. Can you also make it so that css keywords like "red" or "blue" are accepted when entering a color. For the prompt text I think including the type of value it's expecting would make things a lot clearer. The tick marker should also move beside the custom item when it is selected.

**Comment by ingridt123** [comment]
@Arthelon Made all changes as suggested above. Thanks!

**Comment by Arthelon** [comment]
@ingridt123 thanks for the PR. merged.

**Comment by ingridt123** [comment]
@Arthelon  Thanks!!! :)

**Pull request merged**
